# Generated by Django 4.2.5 on 2023-12-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_purchasepayment1_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_account',
            name='paid_cheque',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan_account',
            name='paid_upi',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan_account',
            name='recieved_cheque',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan_account',
            name='recieved_upi',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
