# Generated by Django 4.2.5 on 2023-12-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_loan_account_paid_cheque_loan_account_paid_upi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_account',
            name='bank_acc_number',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
