# Generated by Django 4.2.5 on 2023-12-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_loan_account_paid_bank_acc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_transaction',
            name='bank_acc_number',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan_transaction',
            name='recieved_cheque',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan_transaction',
            name='recieved_upi',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
