# Generated by Django 4.2.5 on 2023-12-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0055_loan_transaction_bank_acc_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='balance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
