# Generated by Django 4.2.5 on 2023-12-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_vendor_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='balance',
            new_name='balance_amount',
        ),
    ]
