# Generated by Django 4.2.5 on 2023-12-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_rename_balance_vendor_balance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='grand_total',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
