# Generated by Django 4.2.5 on 2023-12-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0058_alter_purchaseorder_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='amtreceived',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='paymentamount',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
