# Generated by Django 4.2.5 on 2023-12-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0059_alter_purchasepayment_amtreceived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment1',
            name='amountdue',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment1',
            name='billamount',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment1',
            name='payments',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
