# Generated by Django 4.2.5 on 2023-12-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0060_alter_purchasepayment1_amountdue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='amtreceived',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='paymentamount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recurring_bill',
            name='balance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recurring_bill',
            name='paid_amount',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
