# Generated by Django 4.2.5 on 2024-01-01 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0063_alter_purchasebill_amtrecvd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
    ]
